#!/bin/bash

set -e

cd "$(dirname "$0")"

rm -rf dist
mkdir dist

for APP in *; do
    if [ -f "$APP/webapp/manifest.json" ]; then
        echo "Build $APP"

        mkdir "dist/$APP"
        cp -r "$APP/webapp/" "dist/$APP/"
        cp xs-app-for-apps.json "dist/$APP/xs-app.json"
        cd "dist/$APP"
        zip -r -o manifest-bundle.zip manifest.json i18n
        cd "../.."
    fi
done